#!/bin/sh

# Repique en el puerto
iptables -N toc
iptables -A toc -p udp --dport 11111 -m recent --set --name toc -j DROP
iptables -A toc -m recent --remove --name toc

# Ya repicado lo suficiente
iptables -N paso
iptables -A paso -m recent --remove --name toc
iptables -A paso -p tcp --dport ssh -j ACCEPT
# ... y otros posibles servicios también ocultos


iptables -A INPUT -m recent --rcheck --hitcount 3 --name toc -j paso
iptables -A INPUT -j toc
